apiVersion: apps/v1
kind: Deployment
metadata:
  name: jquery-static
  namespace: jquery
spec:
  selector:
    matchLabels:
      app: jquery
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jquery
    spec:
      containers:
      - name: jquery
        image: 865563157914.dkr.ecr.ap-south-1.amazonaws.com/jequery:number
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: jquery
---
apiVersion: v1
kind: Service
metadata:
  name: jquery-svc
  namespace: jquery
spec:
  selector: 
    app: jquery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
